version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: huskeseddel-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/huskeseddel.db
      - SECRET_KEY=${SECRET_KEY:-huskeseddel-secret-key-change-in-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - huskeseddel-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: huskeseddel-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - huskeseddel-network

networks:
  huskeseddel-network:
    driver: bridge

volumes:
  huskeseddel-data:
    driver: local