version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: huskeseddel-backend
    ports:
      - "3041:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/huskeseddel.db
      - SECRET_KEY=huskeseddel-production-secret-key
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: huskeseddel-frontend
    ports:
      - "3042:80"
    depends_on:
      - backend
    restart: unless-stopped